apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
          command:
            - sh
            - -c
            - until pg_isready -h postgres -p 5432; do sleep 2; done
      containers:
        - name: backend
          image: 485104726319.dkr.ecr.ca-central-1.amazonaws.com/taskflow/api:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
