apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.secrets.user | quote }}
  password: {{ .Values.secrets.password | quote }}
  database: {{ .Values.secrets.database | quote }}
