apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-user: {{ .Values.secrets.dbUser | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  db-name: {{ .Values.secrets.dbName | quote }}
