apiVersion: v2
name: taskflow
description: TaskFlow umbrella chart (frontend + backend + postgres)
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: frontend
    version: 1.0.0
    repository: "file://../frontend"
    alias: frontend
  - name: backend
    version: 1.0.0
    repository: "file://../backend"
    alias: backend
  - name: postgres
    version: 1.0.0
    repository: "file://../postgres"
    alias: postgres
