image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

persistence:
  enabled: false
  size: 10Gi
  storageClassName: standard

secrets:
  password: postgres
  user: postgres
  database: taskflow_db

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
